//! The [`Report`] sink.

use core::{fmt, hash::Hash};

use super::Sink;
use crate::{ClassifiedDiagnostic, code};

/// A [sink](Sink) that eagerly reports each diagnostic it receives.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Report<C> {
    /// The configuration settings that will be passed along to [`ariadne`].
    config: ariadne::Config,

    /// The source cache.
    cache: C,
}

impl<C> Report<C> {
    /// Constructs a new sink.
    ///
    /// # See Also
    ///
    /// - [`from_sources`](Self::from_sources)
    pub const fn new(cache: C) -> Self {
        Self {
            config: ariadne::Config::new(),
            cache,
        }
    }

    /// Sets the configuration settings for reports generated by this sink.
    ///
    /// Unlike [`with_config`], this borrows `self`, so it cannot be used as the last builder method
    /// in a chain; however, it can be called by itself without reassigning `self`'s owner.
    ///
    /// # See Also
    ///
    /// - [`with_config`]
    ///
    /// [`with_config`]: Self::with_config
    pub fn set_config(&mut self, config: ariadne::Config) -> &mut Self {
        self.config = config;
        self
    }

    /// Sets the configuration settings for reports generated by this sink.
    ///
    /// Unlike [`set_config`], this consumes `self`, so it can be used as the last builder method in
    /// a chain; however, it cannot be called by itself without reassigning `self`'s owner.
    ///
    /// # See Also
    ///
    /// - [`set_config`]
    ///
    /// [`set_config`]: Self::with_config
    pub fn with_config(mut self, config: ariadne::Config) -> Self {
        self.set_config(config);
        self
    }
}

impl Report<()> {
    /// Constructs a new sink from a collection of sources.
    ///
    /// See [`ariadne::sources`] for more details.
    ///
    /// # See Also
    ///
    /// - [`new`](Self::new)
    pub fn from_sources<Id, S>(
        sources: impl IntoIterator<Item = (Id, S)>,
    ) -> Report<impl ariadne::Cache<Id>>
    where
        Id: fmt::Display + Hash + PartialEq + Eq + Clone + 'static,
        S: AsRef<str>,
    {
        Report::new(ariadne::sources(sources))
    }
}

impl<S, D, C> Sink<S, D> for Report<C>
where
    S: ariadne::Span + Clone,
    D: code::Discriminant,
    C: ariadne::Cache<S::SourceId>,
{
    fn add(&mut self, diagnostic: ClassifiedDiagnostic<S, D>) {
        let _ = diagnostic.report(self.config.clone(), &mut self.cache);
    }
}
